export const ADD_TO_CART = "ADD_TO_CART";

export const ADJUST_ITEM_QTY = "ADJUST_ITEM_QTY"
export const REMOVE_ITEM_QTY = "REMOVE_ITEM_QTY"
export const LOAD_CURRENT_ITEM = "LOAD_CURRENT_ITEM";

export const CHECKOUT_CART_ITEMS = "CHECKOUT_CART_ITEMS"

export const REMOVE_ALL_CART = "REMOVE_ALL_CART"